name: release
on:
  release:
    types: [prereleased, released]

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build
        run: |
          go run build/main.go
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: k6